export { default as MovieInformation } from "./MovieInformation/MovieInformation";
export { default as Main } from "./Main/Main";
export { default as NavBar } from "./NavBar/NavBar";
export { default as ProfileDetail } from "./ProfileDetail/ProfileDetail";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as ProfileList } from "./ProfileList/ProfileList";
export { default as Profile } from "./Profile/Profile";
export { default as RatedCards } from "./RatedCards/RatedCards";
export { default as FeaturedActivities } from "./FeaturedActivities/FeaturedActivities";
